######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 14 10:14:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += help.h mainwindow.h options.h
FORMS += help.ui mainwindow.ui options.ui
SOURCES += help.cpp main.cpp mainwindow.cpp options.cpp
RESOURCES += Images.qrc
